### ISSUE TITLE
Thoughts on assignment

### ISSUE THREAD

**Issue by benspector-mls** [The-Marcy-Lab-School/2-2-0-assignment#1]
- can we give an example of the runner pattern in the instructions? Something like the code below. I think it would be helpful to re-explain what this is and describe the value of it.

```js
// no runner:

const rollDice = () => Math.floor(Math.random * 6);

const roll1 = rollDice();
const roll2 = rollDice();

console.log(`you rolled a ${roll1 + roll2}!`);

// runner pattern:
const rollDice = () => Math.floor(Math.random * 6);
const printRoll = (roll1, roll2) => console.log(`you rolled a ${roll1 + roll2}!`);
const main = () => {
  const roll1 = rollDice();
  const roll2 = rollDice();
  printRoll(roll1, roll2);
}
main();
```

- we should point out where they can see this (in the `modify.js` file at the bottom)
- Can we include instructions for _how_ to use the modify file? (live server the modify.html file and open the console)
- Instructions for Question 7 were pretty confusing. I'll write up another draft
- The last question has some typos that don't match what the tests expect. I'll write up a draft.

**Comment by MostlyFocusedMike** [comment]
I think we're ok here not to add this much, as the runner pattern has been mentioned in all of mod 1's labs (soon to be 3 instead of 2). It's not _critical_ for them to know what it is here, and if they don't know it they can take that curiosity and look it up. These DOM ones have so much text I want to keep it focused. All the clarification edits looked good
